### ISSUE TITLE
Passwords validation

### ISSUE THREAD

**Issue by mazda91** [cairn-monnaie/CairnB2B#13]
**Problème 1** : des mots de passe trop simples sont, pour l'instant, possibles avec les contraintes imposées (notamment les mots de passe répétitifs). Cyclos propose deux options de validation de mot de passe pour "mots de passe évident" et "mots de passe répétitifs". Il faut donc trouver un moyen d'intégrer la réponse fournie par Cyclos à notre formulaire d'inscription.

**Problème 2** l'action Registration de FOSUserBundle n'a pas été surchargée, mais est simplement modifiée via les FOSUserEvents pour adapter l'inscription à nos besoins (notamment pour créer une entité Cyclos correspondante). Il faudrait donc utiliser l'Event fos_user.registration.completed pour récupérer le mot de passe juste après la soumission, mais avant la validation, pour tester le mot de passe dans Cyclos car sinon, la validation serait bonne côté Symfony, mais pas côté Cyclos.

**Comment by mazda91** [comment]
**Solution envisageable** : chaque utilisateur a un mot de passe généré qui n'a rien à voir avec le mot de passe côté Symfony. Ainsi, on s'assurerait de la validité du mdp côté Cyclos, et on éviterait toute dissociation des bases de données. Cependant, on ne profiterait pas de l'algo Cyclos pour valider les mdp côté Symfony

**Comment by janssens** [comment]
Ta solution ne me plait pas car elle ne permet pas le passage nécessaire vers un modèle ou c'est utilisateur cyclos qui fait les transactions demandé par l'utilisateur symfony et non l'admin cyclos.

Ce qu'il faudrait faire c'est ajouter une contrainte customisé sur le mdp symfony qui interroge cyclos sur la validité du mdp. soit via un webservice existant type "check_password_validity" soit en créant un faux compte cyclos qu'on supprime dans la foulée si le webservice n'existe pas.

**Comment by mazda91** [comment]
Il n'y a pas de service de validation de mot de passe.
Pour la 1ère solution, 2 façons de faire : 
       *pouvoir accéder à un service dans la classe User vu que c'est là que l'entité est validée(mauvaise pratique)
      *transformer le formulaire d'inscription en service, y injecter le service nécessaire  pour créer l'utilisateur Cyclos  en écoutant un évenement POST_SUBMIT et ajouter une erreur dans le formulaire en cas d'erreur de validation Cyclos (tiré par les cheveux)
Pour la 2ème proposition( le faux compte cyclos, exactement ce que j'étais en train de faire), il y a un souci : aucun FOSUserEvent ne permet de rediriger l'utilisateur vers le formulaire après la validation de celui-ci par le service validator. Du coup, impossible de créer le faux compte après coup et, en cas d'erreur, rediriger vers le formulaire avec les champs préremplis et l'erreur affichée.

Plutôt que de bidouiller en utilisant les listeners fournis par FOSUserBundle, je compte surcharger complètement la logique d'inscription. Qu'en penses-tu ?

**Comment by janssens** [comment]
je pensais à ça
https://symfony.com/doc/current/reference/constraints/Callback.html
qui donc, si cyclos refuse le pswd, refuse que le formulaire symfony soit validé
